# Meta data
num_classes: 9
random_seed: 1227
image_size: 256
num_channels: 3
class_label_map: 
  backyard: 0
  bathroom: 1
  bedroom: 2
  diningRoom: 3
  frontyard: 4
  hall: 5
  kitchen: 6
  livingRoom: 7
  plan: 8
  
# Training-related configs shared by all training scripts
batch_size: 32
patience: 3

# AWS configs
py_version: py310
framework_version: 2.12.0
volume_size: 30
s3_bucket: yang-ml-homepartners
s3_key: scene-classification
model_dir: /opt/ml/model
output_path: s3://yang-ml-homepartners/scene-classification/models
code_location: s3://yang-ml-homepartners/scene-classification/code
dfw_s3_path: s3://hpa-data-lake/raw/mls/resized_photos/dfw/websize
best_model_s3_path: s3://yang-ml-homepartners/scene-classification/models/fine-tune-hpo-230710-1525-030-cf221d8d/output/model.tar.gz
# Spot training
train_use_spot_instances: true
max_run: 86400
max_retry_attempts: 2
checkpoint_s3_uri: s3://yang-ml-homepartners/scene-classification/checkpoints

# File system
src_dir_path: /home/ec2-user/SageMaker/ds_sagemaker_scene_classification/src

# These are group configs specific to the entry scripts
defaults:
  - _self_
  - fine_tune: fine_tune