# Processing inputs
output_key: data/processed/long
start_date: 2013-01-31
end_date: 2023-06-30
forecast_horizon: 36  # Thirty-six months (3 years)

# Training fixed hyperparameters
freq: M
m: 12 # Single seasonality for monthly data
window_length: 42 # Selected to ensure 13 train-validation splits
step_length: 1 # Selected to ensure 13 train-validation splits
metric: rmse # Also possible: mae, mse, mape, smape
pred_interval: 0.9 # 90% prediction intervals

# Persistence
model_key: 'models/long'