# AWS config
s3_bucket: yang-ml-sagemaker
s3_key: census-income-classification
model_dir: /opt/ml/model
output_path: s3://yang-ml-sagemaker/census-income-classification/models
code_location: s3://yang-ml-sagemaker/census-income-classification/code
volume_size: 30
# Spot training
use_spot_instances: true
max_run: 86400
max_retry_attempts: 2
checkpoint_s3_uri: s3://yang-ml-sagemaker/object-detection/checkpoints
# File system
src_dir_path: /home/ec2-user/SageMaker/census-income-classification/src
notebook_dir_path: /home/ec2-user/SageMaker/census-income-classification/notebooks
container_dir_path: /home/ec2-user/SageMaker/census-income-classification/container
# Meta data for ingestion and uploading to s3
train_data_url: https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data
test_data_url: https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test
csv_header:
  - age
  - workclass
  - fnlwgt
  - education
  - education_num
  - marital_status
  - occupation
  - relationship
  - race
  - gender
  - capital_gain
  - capital_loss
  - hours_per_week
  - native_country
  - income_bracket
target: income_bracket
validation_size: 0.2
random_seed: 12
header: false
patience: 3
# Optuna
stack_name: optuna-stack
defaults:
  - _self_
  - tf_keras: tf_keras