# Training-related configs shared by all training scripts
num_folds: 10
patience: 1
# AWS configs
py_version: py310
framework_version: 2.13.0
volume_size: 30
s3_bucket: yang-ml-sagemaker
s3_key: micro-business-forecast
model_dir: /opt/ml/model
processing_job_input: /opt/ml/processing/input
processing_job_output: /opt/ml/processing/output
output_path: s3://yang-ml-sagemaker/micro-business-forecast/models
code_location: s3://yang-ml-sagemaker/micro-business-forecast/code
# Spot training
use_spot_instances: true
max_run: 86400
max_retry_attempts: 2
checkpoint_s3_uri: s3://yang-ml-sagemaker/micro-business-forecast/checkpoints
# File system
src_dir_path: /home/ec2-user/SageMaker/micro-business-forecast/src
root_dir_path: /home/ec2-user/SageMaker/micro-business-forecast

# These are group configs specific to the entry scripts
defaults:
  - _self_
  - gru: gru