# AWS config
s3_bucket: fraud-detection-classification
model_dir: /opt/ml/model
output_path: s3://fraud-detection-classification/models
code_location: s3://fraud-detection-classification/code
ecr_repository: fraud-detection
volume_size: 30
# Spot training
use_spot_instances: true
max_run: 86400
max_wait: 86400
max_retry_attempts: 2
checkpoint_s3_uri: s3://fraud-detection-classification/checkpoints
# File system
src_dir_path: /home/ec2-user/SageMaker/credit-card-fraud-detection/src
notebook_dir_path: /home/ec2-user/SageMaker/credit-card-fraud-detection/notebooks
docker_dir_path: /home/ec2-user/SageMaker/credit-card-fraud-detection/docker

# Features
features:
  numerical:
    - creditLimit
    - availableMoney
    - transactionAmount
    - currentBalance
  categorical:
    - merchantName
    - acqCountry
    - merchantCountryCode
    - posEntryMode
    - posConditionCode
    - merchantCategoryCode
    - cardPresent
    - expirationDateKeyInMatch
    - transactionType
    - cardCVV
    - enteredCVV
    - cardLast4Digits
  date:
    - currentExpDate
    - accountOpenDate
    - dateOfLastAddressChange
    - transactionDateTime
  target: isFraud
  id: accountNumber

stack_name: fraud-detection

# Training global
random_seed: 1227

# Group config
defaults:
  - _self_
  - xgboost: xgboost
  - lightgbm: lightgbm
