transfer_entry_point: transfer_learning.py
inference_entry_point: inference.py
instance_type: ml.p3.2xlarge
instance_count: 1
base_job_name: od-built-in-training
base_tuning_job_name: od-built-in-hpo
endpoint_name: od-built-in-endpoint
model_name: od-built-in-model