# Conda Environment Setup ----
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f conda_environment_setup/environment_setup.yaml
#    conda env update --file conda_environment_setup/environment_setup.yaml --prune
#    conda env export --name python_for_machine_learning > envname.yml
#    conda env remove --name python_for_machine_learning
#    conda activate python_for_machine_learning
#    conda deactivate
#    conda env list

name: python_for_machine_learning
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.9.6
  - pip
  - pip:
      # Core Data
      - numpy==1.20.2
      - pandas==1.3.3
      - pandas_datareader==0.10.0
      - SciPy==1.5.4
      - datatable==1.0.0

      # Modeling & Machine Learning
      - scikit-learn==0.23.2
      - pycaret==2.3.9
      - kneed
      - yellowbrick
      - mlflow
      - mlflow-skinny
      - optuna
      - scikit-optimize
      - tune-sklearn

      # AWS
      - boto3
      - psycopg2==2.8.6

      # Jupyter
      - jupyterlab==3.0.14
      - jupyterlab-server==2.8.0
      - ipywidgets==7.6.3
      
      # EDA
      - pandas-profiling

      # Reporting
      - stargazer==0.0.5

      # Visualization
      - matplotlib==3.3.4
      - plotnine==0.7.1
      - mizani==0.7.2
      - plotly==4.14.3
      - altair==4.1.0
      - graphviz==2.46.0
      - python-graphviz==0.20 