# AWS
s3_bucket: yang-ml-sagemaker
s3_key: insect-pest-classification
model_dir: /opt/ml/model
code_location: s3://yang-ml-sagemaker/insect-pest-classification/code
output_path: s3://yang-ml-sagemaker/insect-pest-classification/models
volume_size: 30
# Spot training
use_spot_instances: true
max_run: 86400
max_retry_attempts: 2
checkpoint_s3_uri: s3://yang-ml-sagemaker/insect-pest-classification/checkpoints
# File system
src_dir_path: /home/ec2-user/SageMaker/incest-classification/src
notebook_dir_path: /home/ec2-user/SageMaker/incest-classification/notebooks
# Meta data for ingestion
val_size: 6288
max_samples: 200 
image_size: 256
batch_size: 32
num_channels: 3
num_classes: 102
shuffle: true
random_seed: 1227

defaults:
  - _self_
  - baseline: baseline
  - fine_tune: fine_tune