name: Check Dependencies

on:
  push:
    paths:
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true

    - name: Create Conda Environment
      shell: bash -l {0}
      run: |
        conda create --name myenv python=3.9.12

    # This will fail if some dependencies are imcompatible
    - name: Install requirements
      shell: bash -l {0}
      run: |
        conda activate myenv
        conda install pip
        pip install -r requirements.txt

    - name: Check requirements
      shell: bash -l {0}
      run: |
        conda activate myenv
        python -m pip check
