# AWS config
s3_bucket: yang-ml-sagemaker
s3_key: tenant-experience
model_dir: /opt/ml/model
output_path: s3://yang-ml-sagemaker/tenant-experience/models
code_location: s3://yang-ml-sagemaker/tenant-experience/code
ecr_repository: ml-sagemaker
volume_size: 30
py_version: py3
# Spot training
use_spot_instances: true
max_run: 86400
max_wait: 86400
max_retry_attempts: 2
checkpoint_s3_uri: s3://yang-ml-sagemaker/tenant-experience/checkpoints
# File system
src_dir_path: /home/ec2-user/SageMaker/tenant-experience/src
notebook_dir_path: /home/ec2-user/SageMaker/tenant-experience/notebooks
docker_dir_path: /home/ec2-user/SageMaker/tenant-experience/docker
# Model and Transformer 
model_name_prefix: tenant-experience-xgboost
transformer_instance_count: 1
transformer_instance_type: ml.c5.xlarge # 4 vCPU, 8 GiB RAM
transformer_strategy: MultiRecord
transformer_output_path: s3://yang-ml-sagemaker/tenant-experience/batch-transform
transformer_max_concurrent_transforms: 2 
transformer_max_payload: 25 # Max concurrent transforms * max payload cannot exceed 100 mb
transformer_base_transform_job_name: tenant-experience-xgboost-transform 

# Optuna
stack_name: tenant-experience

# Group config
defaults:
  - _self_
  - xgboost: xgboost